### ISSUE TITLE
ion/src/device/n0110/flash.ld:187 cannot move location counter backwards (from 20038230 to 20038000) when compiling with Omega

### ISSUE THREAD

**Issue by CacahueteSansSel** [CacahueteSansSel/leterminal#3]
Here is the complete output of the command : [full_stacktrace.txt](https://github.com/CacahueteSansSel/leterminal/files/5960777/full_stacktrace.txt). Probably reducing *let*'s final size will fix this.

**Comment by CacahueteSansSel** [comment]
Commit 94f5c34 does not fix the issue, it's probably a problem with the *Omega-dev* branch.

**Comment by M4xi1m3** [comment]
This is because the compiled firmware uses too much memory. Remember: Omega has increased python heap and script store. Try decreasing one or both and recompiling. Python heap is in apps/code/app.h, k_pythonHeapSize.

**Comment by CacahueteSansSel** [comment]
Understood ! I will try that and close the issue if that works.

**Comment by CacahueteSansSel** [comment]
Issue fixed, thanks for your help !
