### ISSUE TITLE
Switching back to user "Cacahuete" when using any commands

### ISSUE THREAD

**Issue by ArtichOwO** [CacahueteSansSel/leterminal#7]
Same as https://github.com/CacahueteSansSel/leterminal/issues/5, but reverse

**Comment by CacahueteSansSel** [comment]
I was not able to reproduce this bug with my version, but I will rework the entire system this evening (can't do that now).

**Comment by CacahueteSansSel** [comment]
Normally fixed in 3013b18. You can reopen this issue if it shows up again
